name: Bump version and create release

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'What kind of release is this?'
        required: false
        default: 'minor'
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: ${{ inputs.bump-type }}

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag-name: ${{ steps.bump.outputs.current-version }}
          release_name: ${{ steps.bump.outputs.current-version }}
